# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 00:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('depth', models.IntegerField()),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='trader.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_status', models.CharField(choices=[('sd', 'SOLD'), ('oh', 'ON HOLD'), ('av', 'AVAILABLE')], max_length=2)),
                ('created_on', models.DateTimeField()),
                ('primary_image', models.ImageField(upload_to='images/user_upload/')),
                ('secondary_image', models.ImageField(upload_to='images/user_upload/')),
                ('optional_image', models.ImageField(null=True, upload_to='images/user_upload/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_items', to='trader.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_name', models.TextField()),
                ('phone_number', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='saleitem',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='trader.UserProfile'),
        ),
    ]
